controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Gripper
    right_gripper_controller:
      type: velocity_controllers/JointGroupVelocityController

    left_gripper_controller:
      type: velocity_controllers/JointGroupVelocityController

# Velocity Controllers ---------------------------------------
# Gripper
right_gripper_controller:
  ros__parameters:
    joints:
      - gripper_R_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity

left_gripper_controller:
  ros__parameters:
    joints:
      - gripper_L_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity